#ifndef MODULE_CONFIG_H
#define MODULE_CONFIG_H

#define MODULE_FIRMWARE_VERSION_MAJOR 0
#define MODULE_FIRMWARE_VERSION_MINOR 1
#define MODULE_SAMPLE_PERIOD_MS 60000UL
#define MODULE_TRANSMIT_RETRY_LIMIT 3U
#define MODULE_LOW_BATTERY_MV 3300
#define MODULE_CRITICAL_BATTERY_MV 3100
#define MODULE_SENSOR_TIMEOUT_MS 250U

#endif
